version: '3'

services:
  app:
    build:
      context: ./
      target: app
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./app:/app
    networks:
      - network
    command:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000",
      ]

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - network

volumes:
  redis:
    driver: local

networks:
  network:
    driver: bridge