version: '3'

services:
  app:
    build:
      context: ./
      target: app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - network

volumes:
  redis:
    driver: local

networks:
  network:
    driver: bridge